# Undirected land-border pairs (iso3, iso3). Stored once per pair.
BORDERS = [
    ("FRA", "DEU"), ("FRA", "BEL"), ("FRA", "LUX"), ("FRA", "CHE"),
    ("FRA", "ITA"), ("FRA", "ESP"), ("FRA", "AND"), ("FRA", "MCO"),
    ("DEU", "NLD"), ("DEU", "BEL"), ("DEU", "LUX"), ("DEU", "DNK"),
    ("DEU", "POL"), ("DEU", "CZE"), ("DEU", "AUT"), ("DEU", "CHE"),
    ("POL", "CZE"), ("POL", "SVK"), ("POL", "LTU"), ("POL", "BLR"), ("POL", "UKR"),
    ("ESP", "PRT"), ("ESP", "AND"),
    ("ITA", "CHE"), ("ITA", "AUT"), ("ITA", "SVN"), ("ITA", "SMR"), ("ITA", "VAT"),
    ("AUT", "CZE"), ("AUT", "SVK"), ("AUT", "HUN"), ("AUT", "SVN"), ("AUT", "CHE"),
    ("HUN", "SVK"), ("HUN", "UKR"), ("HUN", "ROU"), ("HUN", "SRB"), ("HUN", "HRV"), ("HUN", "SVN"),
    ("ROU", "BGR"), ("ROU", "SRB"), ("ROU", "UKR"), ("ROU", "MDA"),
    ("SRB", "MNE"), ("SRB", "BIH"), ("SRB", "HRV"), ("SRB", "MKD"), ("SRB", "BGR"), ("SRB", "XKX"),
    ("GRC", "BGR"), ("GRC", "MKD"), ("GRC", "ALB"), ("GRC", "TUR"),
    ("NOR", "SWE"), ("NOR", "FIN"), ("NOR", "RUS"),
    ("SWE", "FIN"), ("FIN", "RUS"),
    ("EST", "LVA"), ("EST", "RUS"), ("LVA", "LTU"), ("LVA", "BLR"), ("LVA", "RUS"),
    ("LTU", "BLR"), ("LTU", "RUS"),
    ("BLR", "UKR"), ("BLR", "RUS"), ("UKR", "MDA"), ("UKR", "RUS"),
    ("HRV", "SVN"), ("HRV", "BIH"), ("HRV", "MNE"),
    ("BIH", "MNE"), ("MNE", "ALB"), ("MNE", "XKX"), ("MKD", "ALB"), ("MKD", "XKX"),
    ("ALB", "XKX"),
    ("AZE", "GEO"), ("AZE", "ARM"), ("AZE", "RUS"), ("AZE", "TUR"),
    ("GEO", "ARM"), ("GEO", "RUS"), ("GEO", "TUR"), ("ARM", "TUR"),
]
