DOMAINS = [
    {"name": "Demographics", "description": "Population, age, migration", "color": "#4C78A8"},
    {"name": "Economy", "description": "GDP, inflation, trade, employment", "color": "#F58518"},
    {"name": "Digital & Connectivity", "description": "Internet, broadband, digital economy", "color": "#54A24B"},
    {"name": "Energy & Green", "description": "Energy, renewables, emissions", "color": "#72B7B2"},
    {"name": "AI & Technology", "description": "R&D, innovation, patents, AI adoption", "color": "#B279A2"},
    {"name": "Governance & Geopolitics", "description": "Memberships, policy and geopolitical events (event layer)", "color": "#E45756"},
]

# domain must match a DOMAINS name; api_code is the series key fetchers emit.
# For series ingested from World Bank the api_code is either the legacy
# Eurostat dataset code (v1 indicators, mapped in sources/world_bank.py) or
# the World Bank series code itself (newer indicators).
# IMPORTANT: seed ids are positional — append new indicators at the END.
INDICATORS = [
    {"domain": "Demographics", "name": "Population", "unit": "persons", "api_code": "demo_pjan", "source_priority": 1,
     "definition": "Total population (World Bank SP.POP.TOTL, mid-year estimate)."},
    {"domain": "Demographics", "name": "Median Age", "unit": "years", "api_code": "demo_pjanind", "source_priority": 1,
     "definition": "Median age of the population on 1 January (Eurostat demo_pjanind, indic_de=MEDAGEPOP)."},
    # Monetary values currently ingested from World Bank in current US$.
    {"domain": "Economy", "name": "GDP", "unit": "USD", "api_code": "nama_10_gdp", "source_priority": 1,
     "definition": "Gross domestic product, current US$ (World Bank NY.GDP.MKTP.CD)."},
    {"domain": "Economy", "name": "GDP per capita", "unit": "USD", "api_code": "sdg_08_10", "source_priority": 1,
     "definition": "GDP per capita, current US$ (World Bank NY.GDP.PCAP.CD)."},
    {"domain": "Economy", "name": "Inflation (HICP)", "unit": "%", "api_code": "prc_hicp_aind", "source_priority": 1,
     "definition": "Annual inflation. Eurostat HICP annual average rate of change where available; otherwise World Bank CPI inflation.",
     "is_proxy": True,
     "proxy_note": "World Bank rows are CPI inflation (FP.CPI.TOTL.ZG), a proxy for Eurostat HICP."},
    {"domain": "Economy", "name": "Unemployment Rate", "unit": "%", "api_code": "une_rt_a", "source_priority": 1,
     "definition": "Unemployment, % of total labour force, ILO modelled estimate (World Bank SL.UEM.TOTL.ZS)."},
    {"domain": "Digital & Connectivity", "name": "Internet Users %", "unit": "%", "api_code": "isoc_ci_ifp_iu", "source_priority": 1,
     "definition": "Individuals using the internet, % of population (World Bank IT.NET.USER.ZS)."},
    {"domain": "Digital & Connectivity", "name": "Broadband Coverage %", "unit": "%", "api_code": "isoc_ci_it_en2", "source_priority": 1,
     "definition": "Fixed broadband subscriptions per 100 people (World Bank IT.NET.BBND.P2).",
     "is_proxy": True,
     "proxy_note": "Subscriptions per 100 people, a proxy for household broadband coverage %."},
    {"domain": "Energy & Green", "name": "Renewable Energy Share %", "unit": "%", "api_code": "nrg_ind_ren", "source_priority": 1,
     "definition": "Renewable energy consumption, % of total final energy consumption (World Bank EG.FEC.RNEW.ZS)."},
    {"domain": "Energy & Green", "name": "Greenhouse Gas Emissions", "unit": "Mt CO2e", "api_code": "env_air_gge", "source_priority": 1,
     "definition": "Total greenhouse gas emissions, Mt CO2 equivalent, AR5 GWPs (World Bank EN.GHG.ALL.MT.CE.AR5)."},
    # --- added in v2 (append-only; ids are positional) ---
    {"domain": "AI & Technology", "name": "R&D Expenditure (% GDP)", "unit": "%", "api_code": "GB.XPD.RSDV.GD.ZS", "source_priority": 1,
     "definition": "Gross domestic expenditure on R&D, % of GDP (World Bank GB.XPD.RSDV.GD.ZS, from UNESCO UIS)."},
    {"domain": "AI & Technology", "name": "Researchers in R&D", "unit": "per million people", "api_code": "SP.POP.SCIE.RD.P6", "source_priority": 1,
     "definition": "Researchers in R&D per million people (World Bank SP.POP.SCIE.RD.P6, from UNESCO UIS)."},
    {"domain": "AI & Technology", "name": "High-tech Exports %", "unit": "%", "api_code": "TX.VAL.TECH.MF.ZS", "source_priority": 1,
     "definition": "High-technology exports, % of manufactured exports (World Bank TX.VAL.TECH.MF.ZS)."},
    {"domain": "AI & Technology", "name": "Patent Applications (residents)", "unit": "applications", "api_code": "IP.PAT.RESD", "source_priority": 1,
     "definition": "Patent applications by residents (World Bank IP.PAT.RESD, from WIPO)."},
    {"domain": "AI & Technology", "name": "Scientific Journal Articles", "unit": "articles", "api_code": "IP.JRN.ARTC.SC", "source_priority": 1,
     "definition": "Scientific and technical journal articles (World Bank IP.JRN.ARTC.SC, from NSF)."},
    {"domain": "AI & Technology", "name": "AI Adoption by Enterprises %", "unit": "%", "api_code": "isoc_eb_ai", "source_priority": 1,
     "definition": "Enterprises using at least one artificial intelligence (AI) technology, % of enterprises with 10+ employees (Eurostat isoc_eb_ai)."},
    {"domain": "AI & Technology", "name": "ICT Specialists %", "unit": "%", "api_code": "isoc_sks_itspt", "source_priority": 1,
     "definition": "ICT specialists, % of total employment (Eurostat isoc_sks_itspt)."},
    {"domain": "Economy", "name": "Government Debt (% GDP)", "unit": "%", "api_code": "GC.DOD.TOTL.GD.ZS", "source_priority": 1,
     "definition": "Central government debt, total, % of GDP (World Bank GC.DOD.TOTL.GD.ZS, IMF GFS basis).",
     "is_proxy": True,
     "proxy_note": "Central government debt (IMF GFS), a proxy for Maastricht general government gross debt; coverage is sparse for some countries."},
    {"domain": "Economy", "name": "Trade Balance (% GDP)", "unit": "%", "api_code": "NE.RSB.GNFS.ZS", "source_priority": 1,
     "definition": "External balance on goods and services, % of GDP (World Bank NE.RSB.GNFS.ZS)."},
    {"domain": "Economy", "name": "FDI Net Inflows (% GDP)", "unit": "%", "api_code": "BX.KLT.DINV.WD.GD.ZS", "source_priority": 1,
     "definition": "Foreign direct investment, net inflows, % of GDP (World Bank BX.KLT.DINV.WD.GD.ZS)."},
    {"domain": "Demographics", "name": "Fertility Rate", "unit": "births per woman", "api_code": "SP.DYN.TFRT.IN", "source_priority": 1,
     "definition": "Total fertility rate, births per woman (World Bank SP.DYN.TFRT.IN)."},
    {"domain": "Demographics", "name": "Life Expectancy", "unit": "years", "api_code": "SP.DYN.LE00.IN", "source_priority": 1,
     "definition": "Life expectancy at birth, total, years (World Bank SP.DYN.LE00.IN)."},
    {"domain": "Demographics", "name": "Urban Population %", "unit": "%", "api_code": "SP.URB.TOTL.IN.ZS", "source_priority": 1,
     "definition": "Urban population, % of total population (World Bank SP.URB.TOTL.IN.ZS)."},
    {"domain": "Demographics", "name": "Net Migration", "unit": "persons", "api_code": "SM.POP.NETM", "source_priority": 1,
     "definition": "Net migration, total number of immigrants minus emigrants (World Bank SM.POP.NETM)."},
    {"domain": "Energy & Green", "name": "CO2 Emissions per Capita", "unit": "t CO2e per person", "api_code": "EN.GHG.CO2.PC.CE.AR5", "source_priority": 1,
     "definition": "CO2 emissions excluding LULUCF, tonnes per capita, AR5 (World Bank EN.GHG.CO2.PC.CE.AR5)."},
    {"domain": "Energy & Green", "name": "Energy Imports Net %", "unit": "%", "api_code": "EG.IMP.CONS.ZS", "source_priority": 1,
     "definition": "Energy imports, net, % of energy use (World Bank EG.IMP.CONS.ZS, from IEA aggregates); series ends mid-2010s."},
]

SOURCES = [
    {"name": "Eurostat", "organization": "European Commission", "url": "https://ec.europa.eu/eurostat",
     "api_endpoint": "https://ec.europa.eu/eurostat/api/dissemination",
     "reliability_score": 0.95, "license": "CC BY 4.0", "redistributable": True, "update_frequency": "varies"},
    {"name": "ECB", "organization": "European Central Bank", "url": "https://data.ecb.europa.eu",
     "api_endpoint": "https://data-api.ecb.europa.eu/service",
     "reliability_score": 0.95, "license": "ECB reuse policy (attribution)", "redistributable": True, "update_frequency": "daily"},
    {"name": "OECD", "organization": "OECD", "url": "https://data.oecd.org",
     "api_endpoint": "https://sdmx.oecd.org/public/rest",
     "reliability_score": 0.92, "license": "OECD terms (attribution)", "redistributable": True, "update_frequency": "varies"},
    {"name": "World Bank", "organization": "World Bank", "url": "https://data.worldbank.org",
     "api_endpoint": "https://api.worldbank.org/v2",
     "reliability_score": 0.9, "license": "CC BY 4.0", "redistributable": True, "update_frequency": "annual"},
    {"name": "eurodata curated", "organization": "eurodata project", "url": "https://github.com/eurodata",
     "api_endpoint": None,
     "reliability_score": 0.85, "license": "CC BY 4.0 (compilation); each event cites its primary source",
     "redistributable": True, "update_frequency": "manual"},
]
