# Each entry: iso2, iso3, name, is_transcontinental, is_disputed, note
COUNTRIES = [
    {"iso2": "AL", "iso3": "ALB", "name": "Albania", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "AD", "iso3": "AND", "name": "Andorra", "is_transcontinental": False, "is_disputed": False, "note": "micro-state; expect gaps"},
    {"iso2": "AM", "iso3": "ARM", "name": "Armenia", "is_transcontinental": False, "is_disputed": False, "note": "Caucasus"},
    {"iso2": "AT", "iso3": "AUT", "name": "Austria", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "AZ", "iso3": "AZE", "name": "Azerbaijan", "is_transcontinental": True, "is_disputed": False, "note": "Caucasus"},
    {"iso2": "BY", "iso3": "BLR", "name": "Belarus", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "BE", "iso3": "BEL", "name": "Belgium", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "BA", "iso3": "BIH", "name": "Bosnia and Herzegovina", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "BG", "iso3": "BGR", "name": "Bulgaria", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "HR", "iso3": "HRV", "name": "Croatia", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "CY", "iso3": "CYP", "name": "Cyprus", "is_transcontinental": True, "is_disputed": False, "note": "geographically Asia, politically EU"},
    {"iso2": "CZ", "iso3": "CZE", "name": "Czechia", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "DK", "iso3": "DNK", "name": "Denmark", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "EE", "iso3": "EST", "name": "Estonia", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "FI", "iso3": "FIN", "name": "Finland", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "FR", "iso3": "FRA", "name": "France", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "GE", "iso3": "GEO", "name": "Georgia", "is_transcontinental": True, "is_disputed": False, "note": "Caucasus"},
    {"iso2": "DE", "iso3": "DEU", "name": "Germany", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "GR", "iso3": "GRC", "name": "Greece", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "HU", "iso3": "HUN", "name": "Hungary", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "IS", "iso3": "ISL", "name": "Iceland", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "IE", "iso3": "IRL", "name": "Ireland", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "IT", "iso3": "ITA", "name": "Italy", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "XK", "iso3": "XKX", "name": "Kosovo", "is_transcontinental": False, "is_disputed": True, "note": "disputed; inconsistent source coverage; code XKX/XK"},
    {"iso2": "LV", "iso3": "LVA", "name": "Latvia", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "LI", "iso3": "LIE", "name": "Liechtenstein", "is_transcontinental": False, "is_disputed": False, "note": "micro-state; expect gaps"},
    {"iso2": "LT", "iso3": "LTU", "name": "Lithuania", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "LU", "iso3": "LUX", "name": "Luxembourg", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "MT", "iso3": "MLT", "name": "Malta", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "MD", "iso3": "MDA", "name": "Moldova", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "MC", "iso3": "MCO", "name": "Monaco", "is_transcontinental": False, "is_disputed": False, "note": "micro-state; expect gaps"},
    {"iso2": "ME", "iso3": "MNE", "name": "Montenegro", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "NL", "iso3": "NLD", "name": "Netherlands", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "MK", "iso3": "MKD", "name": "North Macedonia", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "NO", "iso3": "NOR", "name": "Norway", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "PL", "iso3": "POL", "name": "Poland", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "PT", "iso3": "PRT", "name": "Portugal", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "RO", "iso3": "ROU", "name": "Romania", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "RU", "iso3": "RUS", "name": "Russia", "is_transcontinental": True, "is_disputed": False, "note": "transcontinental"},
    {"iso2": "SM", "iso3": "SMR", "name": "San Marino", "is_transcontinental": False, "is_disputed": False, "note": "micro-state; expect gaps"},
    {"iso2": "RS", "iso3": "SRB", "name": "Serbia", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "SK", "iso3": "SVK", "name": "Slovakia", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "SI", "iso3": "SVN", "name": "Slovenia", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "ES", "iso3": "ESP", "name": "Spain", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "SE", "iso3": "SWE", "name": "Sweden", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "CH", "iso3": "CHE", "name": "Switzerland", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "TR", "iso3": "TUR", "name": "Turkey", "is_transcontinental": True, "is_disputed": False, "note": "transcontinental"},
    {"iso2": "UA", "iso3": "UKR", "name": "Ukraine", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "GB", "iso3": "GBR", "name": "United Kingdom", "is_transcontinental": False, "is_disputed": False, "note": None},
    {"iso2": "VA", "iso3": "VAT", "name": "Vatican City", "is_transcontinental": False, "is_disputed": False, "note": "micro-state; expect gaps"},
]
