"""Curated structured events for event-study analysis.

Every entry is a widely documented public fact with a primary source URL.
Dates are ISO strings; end_date is None for point-in-time events.
confidence: 1.0 = officially dated fact; 0.9 = commonly accepted but fuzzy
start/end (e.g. crisis periods). iso3 is None for bloc-/Europe-wide events.
tags and affected_domains are comma-separated; domain names must match
reference.catalog.DOMAINS.
"""

EVENTS = [
    # --- EU / Eurozone / Schengen membership milestones ---
    {"code": "euro-cash-2002", "title": "Euro banknotes and coins introduced",
     "description": "Euro cash replaces national currencies in 12 member states.",
     "event_type": "eurozone_membership", "iso3": None, "bloc_code": "EUROZONE",
     "start_date": "2002-01-01", "end_date": None,
     "source": "European Central Bank", "source_url": "https://www.ecb.europa.eu/euro/intro/html/index.en.html",
     "confidence": 1.0, "tags": "euro,currency", "affected_domains": "Economy"},
    {"code": "eu-enlargement-2004", "title": "EU eastern enlargement (10 states)",
     "description": "CZE, EST, HUN, LVA, LTU, MLT, POL, SVK, SVN, CYP join the EU.",
     "event_type": "eu_membership", "iso3": None, "bloc_code": "EU",
     "start_date": "2004-05-01", "end_date": None,
     "source": "European Union", "source_url": "https://european-union.europa.eu/principles-countries-history/eu-enlargement_en",
     "confidence": 1.0, "tags": "enlargement", "affected_domains": "Economy,Demographics"},
    {"code": "eu-enlargement-2007", "title": "Bulgaria and Romania join the EU",
     "description": "BGR and ROU become EU member states.",
     "event_type": "eu_membership", "iso3": None, "bloc_code": "EU",
     "start_date": "2007-01-01", "end_date": None,
     "source": "European Union", "source_url": "https://european-union.europa.eu/principles-countries-history/eu-enlargement_en",
     "confidence": 1.0, "tags": "enlargement", "affected_domains": "Economy,Demographics"},
    {"code": "hrv-eu-2013", "title": "Croatia joins the EU",
     "description": "Croatia becomes the 28th EU member state.",
     "event_type": "eu_membership", "iso3": "HRV", "bloc_code": "EU",
     "start_date": "2013-07-01", "end_date": None,
     "source": "European Union", "source_url": "https://european-union.europa.eu/principles-countries-history/eu-enlargement_en",
     "confidence": 1.0, "tags": "enlargement", "affected_domains": "Economy"},
    {"code": "hrv-euro-2023", "title": "Croatia adopts the euro",
     "description": "Croatia becomes the 20th euro area member.",
     "event_type": "eurozone_membership", "iso3": "HRV", "bloc_code": "EUROZONE",
     "start_date": "2023-01-01", "end_date": None,
     "source": "European Central Bank", "source_url": "https://www.ecb.europa.eu/press/pr/date/2022/html/ecb.pr220712~e91b4b7c78.en.html",
     "confidence": 1.0, "tags": "euro,currency", "affected_domains": "Economy"},
    {"code": "bgr-euro-2026", "title": "Bulgaria adopts the euro",
     "description": "Bulgaria becomes the 21st euro area member.",
     "event_type": "eurozone_membership", "iso3": "BGR", "bloc_code": "EUROZONE",
     "start_date": "2026-01-01", "end_date": None,
     "source": "Council of the EU", "source_url": "https://www.consilium.europa.eu/en/policies/enlargement-euro-area/",
     "confidence": 1.0, "tags": "euro,currency", "affected_domains": "Economy"},
    {"code": "bgr-rou-schengen-2025", "title": "Bulgaria and Romania fully join Schengen",
     "description": "Land-border checks lifted; full Schengen membership.",
     "event_type": "policy_change", "iso3": None, "bloc_code": "SCHENGEN",
     "start_date": "2025-01-01", "end_date": None,
     "source": "Council of the EU", "source_url": "https://www.consilium.europa.eu/en/policies/schengen-area/",
     "confidence": 1.0, "tags": "schengen,borders", "affected_domains": "Economy,Demographics"},
    {"code": "brexit-referendum-2016", "title": "Brexit referendum",
     "description": "UK votes 51.9% to leave the European Union.",
     "event_type": "election", "iso3": "GBR", "bloc_code": None,
     "start_date": "2016-06-23", "end_date": None,
     "source": "UK Electoral Commission", "source_url": "https://www.electoralcommission.org.uk/who-we-are-and-what-we-do/elections-and-referendums/past-elections-and-referendums/eu-referendum",
     "confidence": 1.0, "tags": "brexit,referendum", "affected_domains": "Economy,Governance & Geopolitics"},
    {"code": "brexit-2020", "title": "United Kingdom leaves the EU",
     "description": "UK formally withdraws from the EU (transition until 2020-12-31).",
     "event_type": "eu_membership", "iso3": "GBR", "bloc_code": "EU",
     "start_date": "2020-01-31", "end_date": "2020-12-31",
     "source": "European Union", "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=OJ:L:2020:029:TOC",
     "confidence": 1.0, "tags": "brexit,withdrawal", "affected_domains": "Economy,Governance & Geopolitics"},

    # --- Financial / economic crises ---
    {"code": "gfc-2008", "title": "Global financial crisis",
     "description": "Lehman Brothers collapse triggers a global banking and demand crisis.",
     "event_type": "financial_crisis", "iso3": None, "bloc_code": None,
     "start_date": "2008-09-15", "end_date": "2009-12-31",
     "source": "ECB", "source_url": "https://www.ecb.europa.eu/ecb/history/html/index.en.html",
     "confidence": 0.9, "tags": "banking,recession", "affected_domains": "Economy"},
    {"code": "euro-debt-crisis-2010", "title": "Euro area sovereign debt crisis",
     "description": "Sovereign spreads widen across the euro area periphery; bailout programmes follow.",
     "event_type": "financial_crisis", "iso3": None, "bloc_code": "EUROZONE",
     "start_date": "2010-04-23", "end_date": "2012-09-06",
     "source": "European Stability Mechanism", "source_url": "https://www.esm.europa.eu/about-esm/history",
     "confidence": 0.9, "tags": "sovereign-debt,bailout", "affected_domains": "Economy"},
    {"code": "grc-bailout-2010", "title": "First Greek bailout programme",
     "description": "EU/IMF agree a EUR 110bn support programme for Greece.",
     "event_type": "financial_crisis", "iso3": "GRC", "bloc_code": None,
     "start_date": "2010-05-02", "end_date": "2018-08-20",
     "source": "European Stability Mechanism", "source_url": "https://www.esm.europa.eu/assistance/greece",
     "confidence": 1.0, "tags": "bailout,sovereign-debt", "affected_domains": "Economy"},
    {"code": "cyp-banking-crisis-2013", "title": "Cypriot banking crisis and bail-in",
     "description": "Cyprus agrees an assistance programme including a bank deposit bail-in.",
     "event_type": "financial_crisis", "iso3": "CYP", "bloc_code": None,
     "start_date": "2013-03-25", "end_date": "2016-03-31",
     "source": "European Stability Mechanism", "source_url": "https://www.esm.europa.eu/assistance/cyprus",
     "confidence": 1.0, "tags": "banking,bail-in", "affected_domains": "Economy"},
    {"code": "chf-depeg-2015", "title": "Swiss franc euro-cap removal",
     "description": "SNB abandons the 1.20 EUR/CHF floor; franc appreciates sharply.",
     "event_type": "policy_change", "iso3": "CHE", "bloc_code": None,
     "start_date": "2015-01-15", "end_date": None,
     "source": "Swiss National Bank", "source_url": "https://www.snb.ch/en/publications/communication/press-releases/2015/pre_20150115",
     "confidence": 1.0, "tags": "currency,monetary-policy", "affected_domains": "Economy"},
    {"code": "grc-referendum-2015", "title": "Greek bailout referendum",
     "description": "Greek voters reject creditor bailout terms; capital controls imposed.",
     "event_type": "election", "iso3": "GRC", "bloc_code": None,
     "start_date": "2015-07-05", "end_date": None,
     "source": "Hellenic Parliament", "source_url": "https://www.hellenicparliament.gr/en/",
     "confidence": 1.0, "tags": "referendum,sovereign-debt", "affected_domains": "Economy,Governance & Geopolitics"},
    {"code": "ecb-app-2015", "title": "ECB launches quantitative easing (APP)",
     "description": "ECB begins large-scale public sector asset purchases.",
     "event_type": "policy_change", "iso3": None, "bloc_code": "EUROZONE",
     "start_date": "2015-03-09", "end_date": "2018-12-31",
     "source": "ECB", "source_url": "https://www.ecb.europa.eu/mopo/implement/app/html/index.en.html",
     "confidence": 1.0, "tags": "monetary-policy,qe", "affected_domains": "Economy"},
    {"code": "ecb-hikes-2022", "title": "ECB starts post-pandemic rate-hike cycle",
     "description": "First ECB rate increase in 11 years in response to inflation.",
     "event_type": "policy_change", "iso3": None, "bloc_code": "EUROZONE",
     "start_date": "2022-07-21", "end_date": "2023-09-20",
     "source": "ECB", "source_url": "https://www.ecb.europa.eu/press/pr/date/2022/html/ecb.mp220721~53e5bdd317.en.html",
     "confidence": 1.0, "tags": "monetary-policy,inflation", "affected_domains": "Economy"},
    {"code": "ngeu-2020", "title": "NextGenerationEU recovery fund agreed",
     "description": "European Council agrees a EUR 750bn joint-borrowing recovery instrument.",
     "event_type": "policy_change", "iso3": None, "bloc_code": "EU",
     "start_date": "2020-07-21", "end_date": None,
     "source": "European Council", "source_url": "https://www.consilium.europa.eu/en/infographics/ngeu-covid-19-recovery-package/",
     "confidence": 1.0, "tags": "fiscal-policy,recovery", "affected_domains": "Economy"},

    # --- Pandemic ---
    {"code": "covid-pandemic-2020", "title": "COVID-19 pandemic",
     "description": "WHO declares COVID-19 a pandemic; lockdowns across Europe.",
     "event_type": "pandemic", "iso3": None, "bloc_code": None,
     "start_date": "2020-03-11", "end_date": "2023-05-05",
     "source": "World Health Organization", "source_url": "https://www.who.int/europe/emergencies/situations/covid-19",
     "confidence": 1.0, "tags": "health,lockdown", "affected_domains": "Economy,Demographics,Digital & Connectivity"},

    # --- War / geopolitics / sanctions ---
    {"code": "crimea-annexation-2014", "title": "Russian annexation of Crimea",
     "description": "Russia annexes Crimea following the Euromaidan revolution.",
     "event_type": "war_conflict", "iso3": "UKR", "bloc_code": None,
     "start_date": "2014-03-18", "end_date": None,
     "source": "UN General Assembly Res. 68/262", "source_url": "https://digitallibrary.un.org/record/767565",
     "confidence": 1.0, "tags": "russia,ukraine,territorial", "affected_domains": "Economy,Governance & Geopolitics"},
    {"code": "eu-sanctions-russia-2014", "title": "First EU sectoral sanctions on Russia",
     "description": "EU imposes economic sanctions over Crimea and eastern Ukraine.",
     "event_type": "sanctions", "iso3": "RUS", "bloc_code": "EU",
     "start_date": "2014-07-31", "end_date": None,
     "source": "Council of the EU", "source_url": "https://www.consilium.europa.eu/en/policies/sanctions-against-russia/",
     "confidence": 1.0, "tags": "russia,sanctions", "affected_domains": "Economy,Energy & Green"},
    {"code": "ukr-invasion-2022", "title": "Russian full-scale invasion of Ukraine",
     "description": "Russia launches a full-scale invasion of Ukraine.",
     "event_type": "war_conflict", "iso3": "UKR", "bloc_code": None,
     "start_date": "2022-02-24", "end_date": None,
     "source": "UN General Assembly Res. ES-11/1", "source_url": "https://digitallibrary.un.org/record/3965290",
     "confidence": 1.0, "tags": "russia,ukraine,war", "affected_domains": "Economy,Energy & Green,Demographics,Governance & Geopolitics"},
    {"code": "eu-sanctions-russia-2022", "title": "EU sanctions packages on Russia (2022–)",
     "description": "Successive EU sanctions packages following the invasion of Ukraine.",
     "event_type": "sanctions", "iso3": "RUS", "bloc_code": "EU",
     "start_date": "2022-02-25", "end_date": None,
     "source": "Council of the EU", "source_url": "https://www.consilium.europa.eu/en/policies/sanctions-against-russia/",
     "confidence": 1.0, "tags": "russia,sanctions", "affected_domains": "Economy,Energy & Green"},
    {"code": "energy-crisis-2021", "title": "European energy crisis",
     "description": "Gas and electricity prices surge from late 2021, amplified by the cut of Russian pipeline supply in 2022.",
     "event_type": "energy_shock", "iso3": None, "bloc_code": "EU",
     "start_date": "2021-09-01", "end_date": "2023-06-30",
     "source": "European Commission", "source_url": "https://energy.ec.europa.eu/topics/markets-and-consumers/actions-and-measures-energy-prices_en",
     "confidence": 0.9, "tags": "gas,electricity,prices", "affected_domains": "Energy & Green,Economy"},
    {"code": "nordstream-sabotage-2022", "title": "Nord Stream pipeline sabotage",
     "description": "Explosions disable the Nord Stream 1 and 2 gas pipelines.",
     "event_type": "energy_shock", "iso3": None, "bloc_code": None,
     "start_date": "2022-09-26", "end_date": None,
     "source": "UN Security Council briefing", "source_url": "https://press.un.org/en/2023/sc15243.doc.htm",
     "confidence": 1.0, "tags": "gas,infrastructure", "affected_domains": "Energy & Green,Economy"},
    {"code": "migration-crisis-2015", "title": "European migrant crisis",
     "description": "Over one million refugees and migrants arrive in the EU, mainly via the Mediterranean.",
     "event_type": "policy_change", "iso3": None, "bloc_code": "EU",
     "start_date": "2015-04-01", "end_date": "2016-03-31",
     "source": "UNHCR", "source_url": "https://www.unhcr.org/europe-emergency.html",
     "confidence": 0.9, "tags": "migration,refugees", "affected_domains": "Demographics,Governance & Geopolitics"},
    {"code": "tur-coup-attempt-2016", "title": "Turkish coup attempt",
     "description": "Failed military coup attempt; state of emergency follows.",
     "event_type": "war_conflict", "iso3": "TUR", "bloc_code": None,
     "start_date": "2016-07-15", "end_date": None,
     "source": "European Parliament briefing", "source_url": "https://www.europarl.europa.eu/thinktank/en/document/EPRS_ATA(2016)586607",
     "confidence": 1.0, "tags": "coup,political-crisis", "affected_domains": "Economy,Governance & Geopolitics"},
    {"code": "fin-nato-2023", "title": "Finland joins NATO",
     "description": "Finland becomes NATO's 31st member.",
     "event_type": "policy_change", "iso3": "FIN", "bloc_code": "NATO",
     "start_date": "2023-04-04", "end_date": None,
     "source": "NATO", "source_url": "https://www.nato.int/cps/en/natohq/news_213448.htm",
     "confidence": 1.0, "tags": "nato,security", "affected_domains": "Governance & Geopolitics"},
    {"code": "swe-nato-2024", "title": "Sweden joins NATO",
     "description": "Sweden becomes NATO's 32nd member.",
     "event_type": "policy_change", "iso3": "SWE", "bloc_code": "NATO",
     "start_date": "2024-03-07", "end_date": None,
     "source": "NATO", "source_url": "https://www.nato.int/cps/en/natohq/news_223446.htm",
     "confidence": 1.0, "tags": "nato,security", "affected_domains": "Governance & Geopolitics"},

    # --- Technology / AI / digital regulation ---
    {"code": "gdpr-2018", "title": "GDPR becomes applicable",
     "description": "The General Data Protection Regulation applies across the EU/EEA.",
     "event_type": "major_technology_policy", "iso3": None, "bloc_code": "EU",
     "start_date": "2018-05-25", "end_date": None,
     "source": "EUR-Lex 2016/679", "source_url": "https://eur-lex.europa.eu/eli/reg/2016/679/oj",
     "confidence": 1.0, "tags": "privacy,data-protection", "affected_domains": "Digital & Connectivity,AI & Technology"},
    {"code": "dma-2023", "title": "Digital Markets Act obligations apply",
     "description": "Gatekeeper obligations under the DMA start applying.",
     "event_type": "major_technology_policy", "iso3": None, "bloc_code": "EU",
     "start_date": "2023-05-02", "end_date": None,
     "source": "EUR-Lex 2022/1925", "source_url": "https://eur-lex.europa.eu/eli/reg/2022/1925/oj",
     "confidence": 1.0, "tags": "competition,platforms", "affected_domains": "Digital & Connectivity,AI & Technology"},
    {"code": "dsa-2024", "title": "Digital Services Act fully applicable",
     "description": "The DSA applies to all intermediaries in the EU.",
     "event_type": "major_technology_policy", "iso3": None, "bloc_code": "EU",
     "start_date": "2024-02-17", "end_date": None,
     "source": "EUR-Lex 2022/2065", "source_url": "https://eur-lex.europa.eu/eli/reg/2022/2065/oj",
     "confidence": 1.0, "tags": "platforms,content", "affected_domains": "Digital & Connectivity"},
    {"code": "chips-act-2023", "title": "European Chips Act enters into force",
     "description": "EU programme to strengthen semiconductor capacity enters into force.",
     "event_type": "major_technology_policy", "iso3": None, "bloc_code": "EU",
     "start_date": "2023-09-21", "end_date": None,
     "source": "EUR-Lex 2023/1781", "source_url": "https://eur-lex.europa.eu/eli/reg/2023/1781/oj",
     "confidence": 1.0, "tags": "semiconductors,industrial-policy", "affected_domains": "AI & Technology,Economy"},
    {"code": "chatgpt-launch-2022", "title": "ChatGPT public launch",
     "description": "OpenAI releases ChatGPT, triggering mass-market generative-AI adoption.",
     "event_type": "technology_milestone", "iso3": None, "bloc_code": None,
     "start_date": "2022-11-30", "end_date": None,
     "source": "OpenAI", "source_url": "https://openai.com/index/chatgpt/",
     "confidence": 1.0, "tags": "ai,generative-ai", "affected_domains": "AI & Technology,Digital & Connectivity"},
    {"code": "ai-act-2024", "title": "EU AI Act enters into force",
     "description": "The world's first comprehensive AI regulation enters into force (staged application from 2025).",
     "event_type": "ai_regulation", "iso3": None, "bloc_code": "EU",
     "start_date": "2024-08-01", "end_date": None,
     "source": "EUR-Lex 2024/1689", "source_url": "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
     "confidence": 1.0, "tags": "ai,regulation", "affected_domains": "AI & Technology,Digital & Connectivity,Economy"},

    # --- Climate / energy policy ---
    {"code": "paris-agreement-2015", "title": "Paris Agreement adopted",
     "description": "Global climate accord adopted at COP21.",
     "event_type": "policy_change", "iso3": None, "bloc_code": None,
     "start_date": "2015-12-12", "end_date": None,
     "source": "UNFCCC", "source_url": "https://unfccc.int/process-and-meetings/the-paris-agreement",
     "confidence": 1.0, "tags": "climate,cop21", "affected_domains": "Energy & Green"},
    {"code": "eu-green-deal-2019", "title": "European Green Deal announced",
     "description": "EU strategy for climate neutrality by 2050 announced.",
     "event_type": "policy_change", "iso3": None, "bloc_code": "EU",
     "start_date": "2019-12-11", "end_date": None,
     "source": "European Commission", "source_url": "https://commission.europa.eu/strategy-and-policy/priorities-2019-2024/european-green-deal_en",
     "confidence": 1.0, "tags": "climate,green-deal", "affected_domains": "Energy & Green,Economy"},
    {"code": "deu-energiewende-2011", "title": "Germany decides nuclear phase-out",
     "description": "After Fukushima, Germany legislates a full nuclear exit.",
     "event_type": "policy_change", "iso3": "DEU", "bloc_code": None,
     "start_date": "2011-06-30", "end_date": None,
     "source": "Bundestag (13th AtG amendment)", "source_url": "https://www.bundestag.de/dokumente/textarchiv/2011/34915890_kw26_de_atomausstieg-205788",
     "confidence": 1.0, "tags": "nuclear,energy-policy", "affected_domains": "Energy & Green"},
    {"code": "deu-nuclear-exit-2023", "title": "Germany shuts last nuclear plants",
     "description": "Germany's final three nuclear power plants go offline.",
     "event_type": "policy_change", "iso3": "DEU", "bloc_code": None,
     "start_date": "2023-04-15", "end_date": None,
     "source": "BMUV", "source_url": "https://www.bmuv.de/en/topics/nuclear-safety",
     "confidence": 1.0, "tags": "nuclear,energy-policy", "affected_domains": "Energy & Green"},
    {"code": "fit-for-55-2021", "title": "Fit for 55 package proposed",
     "description": "EU legislative package to cut emissions 55% by 2030.",
     "event_type": "policy_change", "iso3": None, "bloc_code": "EU",
     "start_date": "2021-07-14", "end_date": None,
     "source": "European Commission", "source_url": "https://commission.europa.eu/strategy-and-policy/priorities-2019-2024/european-green-deal/delivering-european-green-deal_en",
     "confidence": 1.0, "tags": "climate,emissions", "affected_domains": "Energy & Green,Economy"},

    # --- Elections (European Parliament) ---
    {"code": "ep-election-2014", "title": "European Parliament election 2014",
     "description": "8th European Parliament elected.",
     "event_type": "election", "iso3": None, "bloc_code": "EU",
     "start_date": "2014-05-22", "end_date": "2014-05-25",
     "source": "European Parliament", "source_url": "https://www.europarl.europa.eu/election-results-2014/en",
     "confidence": 1.0, "tags": "election,european-parliament", "affected_domains": "Governance & Geopolitics"},
    {"code": "ep-election-2019", "title": "European Parliament election 2019",
     "description": "9th European Parliament elected.",
     "event_type": "election", "iso3": None, "bloc_code": "EU",
     "start_date": "2019-05-23", "end_date": "2019-05-26",
     "source": "European Parliament", "source_url": "https://www.europarl.europa.eu/election-results-2019/en",
     "confidence": 1.0, "tags": "election,european-parliament", "affected_domains": "Governance & Geopolitics"},
    {"code": "ep-election-2024", "title": "European Parliament election 2024",
     "description": "10th European Parliament elected.",
     "event_type": "election", "iso3": None, "bloc_code": "EU",
     "start_date": "2024-06-06", "end_date": "2024-06-09",
     "source": "European Parliament", "source_url": "https://results.elections.europa.eu/",
     "confidence": 1.0, "tags": "election,european-parliament", "affected_domains": "Governance & Geopolitics"},
]
