# NUTS 2 regions (2021 classification), derived from Eurostat's live "geo"
# dimension on nama_10r_2gdp (GDP by NUTS 2 region) 2026-07-16 — the same
# source used to ingest sub-national indicators, so codes are guaranteed to
# match. parent_iso3 links each region to its COUNTRIES entry (geography.parent_id).
# 'Extra-Regio' residual codes (activities not assignable to a region, e.g.
# embassies/offshore) are excluded — not real geographic regions.
NUTS2_REGIONS = [
    {"code": "AL01", "name": "Veri", "parent_iso3": "ALB"},
    {"code": "AL02", "name": "Qender", "parent_iso3": "ALB"},
    {"code": "AL03", "name": "Jug", "parent_iso3": "ALB"},
    {"code": "AT11", "name": "Burgenland", "parent_iso3": "AUT"},
    {"code": "AT12", "name": "Niederösterreich", "parent_iso3": "AUT"},
    {"code": "AT13", "name": "Wien", "parent_iso3": "AUT"},
    {"code": "AT21", "name": "Kärnten", "parent_iso3": "AUT"},
    {"code": "AT22", "name": "Steiermark", "parent_iso3": "AUT"},
    {"code": "AT31", "name": "Oberösterreich", "parent_iso3": "AUT"},
    {"code": "AT32", "name": "Salzburg", "parent_iso3": "AUT"},
    {"code": "AT33", "name": "Tirol", "parent_iso3": "AUT"},
    {"code": "AT34", "name": "Vorarlberg", "parent_iso3": "AUT"},
    {"code": "BE10", "name": "Région de Bruxelles-Capitale/Brussels Hoofdstedelijk Gewest", "parent_iso3": "BEL"},
    {"code": "BE21", "name": "Prov. Antwerpen", "parent_iso3": "BEL"},
    {"code": "BE22", "name": "Prov. Limburg (BE)", "parent_iso3": "BEL"},
    {"code": "BE23", "name": "Prov. Oost-Vlaanderen", "parent_iso3": "BEL"},
    {"code": "BE24", "name": "Prov. Vlaams-Brabant", "parent_iso3": "BEL"},
    {"code": "BE25", "name": "Prov. West-Vlaanderen", "parent_iso3": "BEL"},
    {"code": "BE31", "name": "Prov. Brabant wallon", "parent_iso3": "BEL"},
    {"code": "BE32", "name": "Prov. Hainaut", "parent_iso3": "BEL"},
    {"code": "BE33", "name": "Prov. Liège", "parent_iso3": "BEL"},
    {"code": "BE34", "name": "Prov. Luxembourg (BE)", "parent_iso3": "BEL"},
    {"code": "BE35", "name": "Prov. Namur", "parent_iso3": "BEL"},
    {"code": "BG31", "name": "Severozapaden", "parent_iso3": "BGR"},
    {"code": "BG32", "name": "Severen tsentralen", "parent_iso3": "BGR"},
    {"code": "BG33", "name": "Severoiztochen", "parent_iso3": "BGR"},
    {"code": "BG34", "name": "Yugoiztochen", "parent_iso3": "BGR"},
    {"code": "BG41", "name": "Yugozapaden", "parent_iso3": "BGR"},
    {"code": "BG42", "name": "Yuzhen tsentralen", "parent_iso3": "BGR"},
    {"code": "CH01", "name": "Région lémanique", "parent_iso3": "CHE"},
    {"code": "CH02", "name": "Espace Mittelland", "parent_iso3": "CHE"},
    {"code": "CH03", "name": "Nordwestschweiz", "parent_iso3": "CHE"},
    {"code": "CH04", "name": "Zürich", "parent_iso3": "CHE"},
    {"code": "CH05", "name": "Ostschweiz", "parent_iso3": "CHE"},
    {"code": "CH06", "name": "Zentralschweiz", "parent_iso3": "CHE"},
    {"code": "CH07", "name": "Ticino", "parent_iso3": "CHE"},
    {"code": "CY00", "name": "Kýpros", "parent_iso3": "CYP"},
    {"code": "CZ01", "name": "Praha", "parent_iso3": "CZE"},
    {"code": "CZ02", "name": "Střední Čechy", "parent_iso3": "CZE"},
    {"code": "CZ03", "name": "Jihozápad", "parent_iso3": "CZE"},
    {"code": "CZ04", "name": "Severozápad", "parent_iso3": "CZE"},
    {"code": "CZ05", "name": "Severovýchod", "parent_iso3": "CZE"},
    {"code": "CZ06", "name": "Jihovýchod", "parent_iso3": "CZE"},
    {"code": "CZ07", "name": "Střední Morava", "parent_iso3": "CZE"},
    {"code": "CZ08", "name": "Moravskoslezsko", "parent_iso3": "CZE"},
    {"code": "DE11", "name": "Stuttgart", "parent_iso3": "DEU"},
    {"code": "DE12", "name": "Karlsruhe", "parent_iso3": "DEU"},
    {"code": "DE13", "name": "Freiburg", "parent_iso3": "DEU"},
    {"code": "DE14", "name": "Tübingen", "parent_iso3": "DEU"},
    {"code": "DE21", "name": "Oberbayern", "parent_iso3": "DEU"},
    {"code": "DE22", "name": "Niederbayern", "parent_iso3": "DEU"},
    {"code": "DE23", "name": "Oberpfalz", "parent_iso3": "DEU"},
    {"code": "DE24", "name": "Oberfranken", "parent_iso3": "DEU"},
    {"code": "DE25", "name": "Mittelfranken", "parent_iso3": "DEU"},
    {"code": "DE26", "name": "Unterfranken", "parent_iso3": "DEU"},
    {"code": "DE27", "name": "Schwaben", "parent_iso3": "DEU"},
    {"code": "DE30", "name": "Berlin", "parent_iso3": "DEU"},
    {"code": "DE40", "name": "Brandenburg", "parent_iso3": "DEU"},
    {"code": "DE50", "name": "Bremen", "parent_iso3": "DEU"},
    {"code": "DE60", "name": "Hamburg", "parent_iso3": "DEU"},
    {"code": "DE71", "name": "Darmstadt", "parent_iso3": "DEU"},
    {"code": "DE72", "name": "Gießen", "parent_iso3": "DEU"},
    {"code": "DE73", "name": "Kassel", "parent_iso3": "DEU"},
    {"code": "DE80", "name": "Mecklenburg-Vorpommern", "parent_iso3": "DEU"},
    {"code": "DE91", "name": "Braunschweig", "parent_iso3": "DEU"},
    {"code": "DE92", "name": "Hannover", "parent_iso3": "DEU"},
    {"code": "DE93", "name": "Lüneburg", "parent_iso3": "DEU"},
    {"code": "DE94", "name": "Weser-Ems", "parent_iso3": "DEU"},
    {"code": "DEA1", "name": "Düsseldorf", "parent_iso3": "DEU"},
    {"code": "DEA2", "name": "Köln", "parent_iso3": "DEU"},
    {"code": "DEA3", "name": "Münster", "parent_iso3": "DEU"},
    {"code": "DEA4", "name": "Detmold", "parent_iso3": "DEU"},
    {"code": "DEA5", "name": "Arnsberg", "parent_iso3": "DEU"},
    {"code": "DEB1", "name": "Koblenz", "parent_iso3": "DEU"},
    {"code": "DEB2", "name": "Trier", "parent_iso3": "DEU"},
    {"code": "DEB3", "name": "Rheinhessen-Pfalz", "parent_iso3": "DEU"},
    {"code": "DEC0", "name": "Saarland", "parent_iso3": "DEU"},
    {"code": "DED2", "name": "Dresden", "parent_iso3": "DEU"},
    {"code": "DED4", "name": "Chemnitz", "parent_iso3": "DEU"},
    {"code": "DED5", "name": "Leipzig", "parent_iso3": "DEU"},
    {"code": "DEE0", "name": "Sachsen-Anhalt", "parent_iso3": "DEU"},
    {"code": "DEF0", "name": "Schleswig-Holstein", "parent_iso3": "DEU"},
    {"code": "DEG0", "name": "Thüringen", "parent_iso3": "DEU"},
    {"code": "DK01", "name": "Hovedstaden", "parent_iso3": "DNK"},
    {"code": "DK02", "name": "Sjælland", "parent_iso3": "DNK"},
    {"code": "DK03", "name": "Syddanmark", "parent_iso3": "DNK"},
    {"code": "DK04", "name": "Midtjylland", "parent_iso3": "DNK"},
    {"code": "DK05", "name": "Nordjylland", "parent_iso3": "DNK"},
    {"code": "EE00", "name": "Eesti", "parent_iso3": "EST"},
    {"code": "EL30", "name": "Attiki", "parent_iso3": "GRC"},
    {"code": "EL41", "name": "Voreio Aigaio", "parent_iso3": "GRC"},
    {"code": "EL42", "name": "Notio Aigaio", "parent_iso3": "GRC"},
    {"code": "EL43", "name": "Kriti", "parent_iso3": "GRC"},
    {"code": "EL51", "name": "Anatoliki Makedonia, Thraki", "parent_iso3": "GRC"},
    {"code": "EL52", "name": "Kentriki Makedonia", "parent_iso3": "GRC"},
    {"code": "EL53", "name": "Dytiki Makedonia", "parent_iso3": "GRC"},
    {"code": "EL54", "name": "Ipeiros", "parent_iso3": "GRC"},
    {"code": "EL61", "name": "Thessalia", "parent_iso3": "GRC"},
    {"code": "EL62", "name": "Ionia Nisia", "parent_iso3": "GRC"},
    {"code": "EL63", "name": "Dytiki Elláda", "parent_iso3": "GRC"},
    {"code": "EL64", "name": "Sterea Elláda", "parent_iso3": "GRC"},
    {"code": "EL65", "name": "Peloponnisos", "parent_iso3": "GRC"},
    {"code": "ES11", "name": "Galicia", "parent_iso3": "ESP"},
    {"code": "ES12", "name": "Principado de Asturias", "parent_iso3": "ESP"},
    {"code": "ES13", "name": "Cantabria", "parent_iso3": "ESP"},
    {"code": "ES21", "name": "País Vasco", "parent_iso3": "ESP"},
    {"code": "ES22", "name": "Comunidad Foral de Navarra", "parent_iso3": "ESP"},
    {"code": "ES23", "name": "La Rioja", "parent_iso3": "ESP"},
    {"code": "ES24", "name": "Aragón", "parent_iso3": "ESP"},
    {"code": "ES30", "name": "Comunidad de Madrid", "parent_iso3": "ESP"},
    {"code": "ES41", "name": "Castilla y León", "parent_iso3": "ESP"},
    {"code": "ES42", "name": "Castilla-La Mancha", "parent_iso3": "ESP"},
    {"code": "ES43", "name": "Extremadura", "parent_iso3": "ESP"},
    {"code": "ES51", "name": "Cataluña", "parent_iso3": "ESP"},
    {"code": "ES52", "name": "Comunitat Valenciana", "parent_iso3": "ESP"},
    {"code": "ES53", "name": "Illes Balears", "parent_iso3": "ESP"},
    {"code": "ES61", "name": "Andalucía", "parent_iso3": "ESP"},
    {"code": "ES62", "name": "Región de Murcia", "parent_iso3": "ESP"},
    {"code": "ES63", "name": "Ciudad de Ceuta", "parent_iso3": "ESP"},
    {"code": "ES64", "name": "Ciudad de Melilla", "parent_iso3": "ESP"},
    {"code": "ES70", "name": "Canarias", "parent_iso3": "ESP"},
    {"code": "FI19", "name": "Länsi-Suomi", "parent_iso3": "FIN"},
    {"code": "FI1B", "name": "Helsinki-Uusimaa", "parent_iso3": "FIN"},
    {"code": "FI1C", "name": "Etelä-Suomi", "parent_iso3": "FIN"},
    {"code": "FI1D", "name": "Pohjois- ja Itä-Suomi", "parent_iso3": "FIN"},
    {"code": "FI20", "name": "Åland", "parent_iso3": "FIN"},
    {"code": "FR10", "name": "Ile de France", "parent_iso3": "FRA"},
    {"code": "FRB0", "name": "Centre — Val de Loire", "parent_iso3": "FRA"},
    {"code": "FRC1", "name": "Bourgogne", "parent_iso3": "FRA"},
    {"code": "FRC2", "name": "Franche-Comté", "parent_iso3": "FRA"},
    {"code": "FRD1", "name": "Basse-Normandie", "parent_iso3": "FRA"},
    {"code": "FRD2", "name": "Haute-Normandie", "parent_iso3": "FRA"},
    {"code": "FRE1", "name": "Nord-Pas de Calais", "parent_iso3": "FRA"},
    {"code": "FRE2", "name": "Picardie", "parent_iso3": "FRA"},
    {"code": "FRF1", "name": "Alsace", "parent_iso3": "FRA"},
    {"code": "FRF2", "name": "Champagne-Ardenne", "parent_iso3": "FRA"},
    {"code": "FRF3", "name": "Lorraine", "parent_iso3": "FRA"},
    {"code": "FRG0", "name": "Pays de la Loire", "parent_iso3": "FRA"},
    {"code": "FRH0", "name": "Bretagne", "parent_iso3": "FRA"},
    {"code": "FRI1", "name": "Aquitaine", "parent_iso3": "FRA"},
    {"code": "FRI2", "name": "Limousin", "parent_iso3": "FRA"},
    {"code": "FRI3", "name": "Poitou-Charentes", "parent_iso3": "FRA"},
    {"code": "FRJ1", "name": "Languedoc-Roussillon", "parent_iso3": "FRA"},
    {"code": "FRJ2", "name": "Midi-Pyrénées", "parent_iso3": "FRA"},
    {"code": "FRK1", "name": "Auvergne", "parent_iso3": "FRA"},
    {"code": "FRK2", "name": "Rhône-Alpes", "parent_iso3": "FRA"},
    {"code": "FRL0", "name": "Provence-Alpes-Côte d’Azur", "parent_iso3": "FRA"},
    {"code": "FRM0", "name": "Corse", "parent_iso3": "FRA"},
    {"code": "FRY1", "name": "Guadeloupe", "parent_iso3": "FRA"},
    {"code": "FRY2", "name": "Martinique", "parent_iso3": "FRA"},
    {"code": "FRY3", "name": "Guyane", "parent_iso3": "FRA"},
    {"code": "FRY4", "name": "La Réunion", "parent_iso3": "FRA"},
    {"code": "FRY5", "name": "Mayotte", "parent_iso3": "FRA"},
    {"code": "HR02", "name": "Panonska Hrvatska", "parent_iso3": "HRV"},
    {"code": "HR03", "name": "Jadranska Hrvatska", "parent_iso3": "HRV"},
    {"code": "HR05", "name": "Grad Zagreb", "parent_iso3": "HRV"},
    {"code": "HR06", "name": "Sjeverna Hrvatska", "parent_iso3": "HRV"},
    {"code": "HU11", "name": "Budapest", "parent_iso3": "HUN"},
    {"code": "HU12", "name": "Pest", "parent_iso3": "HUN"},
    {"code": "HU21", "name": "Közép-Dunántúl", "parent_iso3": "HUN"},
    {"code": "HU22", "name": "Nyugat-Dunántúl", "parent_iso3": "HUN"},
    {"code": "HU23", "name": "Dél-Dunántúl", "parent_iso3": "HUN"},
    {"code": "HU31", "name": "Észak-Magyarország", "parent_iso3": "HUN"},
    {"code": "HU32", "name": "Észak-Alföld", "parent_iso3": "HUN"},
    {"code": "HU33", "name": "Dél-Alföld", "parent_iso3": "HUN"},
    {"code": "IE04", "name": "Northern and Western", "parent_iso3": "IRL"},
    {"code": "IE05", "name": "Southern", "parent_iso3": "IRL"},
    {"code": "IE06", "name": "Eastern and Midland", "parent_iso3": "IRL"},
    {"code": "ITC1", "name": "Piemonte", "parent_iso3": "ITA"},
    {"code": "ITC2", "name": "Valle d’Aosta/Vallée d’Aoste", "parent_iso3": "ITA"},
    {"code": "ITC3", "name": "Liguria", "parent_iso3": "ITA"},
    {"code": "ITC4", "name": "Lombardia", "parent_iso3": "ITA"},
    {"code": "ITF1", "name": "Abruzzo", "parent_iso3": "ITA"},
    {"code": "ITF2", "name": "Molise", "parent_iso3": "ITA"},
    {"code": "ITF3", "name": "Campania", "parent_iso3": "ITA"},
    {"code": "ITF4", "name": "Puglia", "parent_iso3": "ITA"},
    {"code": "ITF5", "name": "Basilicata", "parent_iso3": "ITA"},
    {"code": "ITF6", "name": "Calabria", "parent_iso3": "ITA"},
    {"code": "ITG1", "name": "Sicilia", "parent_iso3": "ITA"},
    {"code": "ITG2", "name": "Sardegna", "parent_iso3": "ITA"},
    {"code": "ITH1", "name": "Provincia Autonoma di Bolzano/Bozen", "parent_iso3": "ITA"},
    {"code": "ITH2", "name": "Provincia Autonoma di Trento", "parent_iso3": "ITA"},
    {"code": "ITH3", "name": "Veneto", "parent_iso3": "ITA"},
    {"code": "ITH4", "name": "Friuli-Venezia Giulia", "parent_iso3": "ITA"},
    {"code": "ITH5", "name": "Emilia-Romagna", "parent_iso3": "ITA"},
    {"code": "ITI1", "name": "Toscana", "parent_iso3": "ITA"},
    {"code": "ITI2", "name": "Umbria", "parent_iso3": "ITA"},
    {"code": "ITI3", "name": "Marche", "parent_iso3": "ITA"},
    {"code": "ITI4", "name": "Lazio", "parent_iso3": "ITA"},
    {"code": "LT01", "name": "Sostinės regionas", "parent_iso3": "LTU"},
    {"code": "LT02", "name": "Vidurio ir vakarų Lietuvos regionas", "parent_iso3": "LTU"},
    {"code": "LU00", "name": "Luxembourg", "parent_iso3": "LUX"},
    {"code": "LV00", "name": "Latvija", "parent_iso3": "LVA"},
    {"code": "ME00", "name": "Crna Gora", "parent_iso3": "MNE"},
    {"code": "MK00", "name": "Severna Makedonija", "parent_iso3": "MKD"},
    {"code": "MT00", "name": "Malta", "parent_iso3": "MLT"},
    {"code": "NL11", "name": "Groningen", "parent_iso3": "NLD"},
    {"code": "NL12", "name": "Friesland (NL)", "parent_iso3": "NLD"},
    {"code": "NL13", "name": "Drenthe", "parent_iso3": "NLD"},
    {"code": "NL21", "name": "Overijssel", "parent_iso3": "NLD"},
    {"code": "NL22", "name": "Gelderland", "parent_iso3": "NLD"},
    {"code": "NL23", "name": "Flevoland", "parent_iso3": "NLD"},
    {"code": "NL32", "name": "Noord-Holland", "parent_iso3": "NLD"},
    {"code": "NL34", "name": "Zeeland", "parent_iso3": "NLD"},
    {"code": "NL35", "name": "Utrecht", "parent_iso3": "NLD"},
    {"code": "NL36", "name": "Zuid-Holland", "parent_iso3": "NLD"},
    {"code": "NL41", "name": "Noord-Brabant", "parent_iso3": "NLD"},
    {"code": "NL42", "name": "Limburg (NL)", "parent_iso3": "NLD"},
    {"code": "NO02", "name": "Innlandet", "parent_iso3": "NOR"},
    {"code": "NO06", "name": "Trøndelag", "parent_iso3": "NOR"},
    {"code": "NO07", "name": "Nord-Norge", "parent_iso3": "NOR"},
    {"code": "NO08", "name": "Oslo og Viken", "parent_iso3": "NOR"},
    {"code": "NO09", "name": "Agder og Sør-Østlandet", "parent_iso3": "NOR"},
    {"code": "NO0A", "name": "Vestlandet", "parent_iso3": "NOR"},
    {"code": "NO0B", "name": "Svalbard og Jan Mayen", "parent_iso3": "NOR"},
    {"code": "PL21", "name": "Małopolskie", "parent_iso3": "POL"},
    {"code": "PL22", "name": "Śląskie", "parent_iso3": "POL"},
    {"code": "PL41", "name": "Wielkopolskie", "parent_iso3": "POL"},
    {"code": "PL42", "name": "Zachodniopomorskie", "parent_iso3": "POL"},
    {"code": "PL43", "name": "Lubuskie", "parent_iso3": "POL"},
    {"code": "PL51", "name": "Dolnośląskie", "parent_iso3": "POL"},
    {"code": "PL52", "name": "Opolskie", "parent_iso3": "POL"},
    {"code": "PL61", "name": "Kujawsko-pomorskie", "parent_iso3": "POL"},
    {"code": "PL62", "name": "Warmińsko-mazurskie", "parent_iso3": "POL"},
    {"code": "PL63", "name": "Pomorskie", "parent_iso3": "POL"},
    {"code": "PL71", "name": "Łódzkie", "parent_iso3": "POL"},
    {"code": "PL72", "name": "Świętokrzyskie", "parent_iso3": "POL"},
    {"code": "PL81", "name": "Lubelskie", "parent_iso3": "POL"},
    {"code": "PL82", "name": "Podkarpackie", "parent_iso3": "POL"},
    {"code": "PL84", "name": "Podlaskie", "parent_iso3": "POL"},
    {"code": "PL91", "name": "Warszawski stołeczny", "parent_iso3": "POL"},
    {"code": "PL92", "name": "Mazowiecki regionalny", "parent_iso3": "POL"},
    {"code": "PT11", "name": "Norte", "parent_iso3": "PRT"},
    {"code": "PT15", "name": "Algarve", "parent_iso3": "PRT"},
    {"code": "PT19", "name": "Centro (PT)", "parent_iso3": "PRT"},
    {"code": "PT1A", "name": "Grande Lisboa", "parent_iso3": "PRT"},
    {"code": "PT1B", "name": "Península de Setúbal", "parent_iso3": "PRT"},
    {"code": "PT1C", "name": "Alentejo", "parent_iso3": "PRT"},
    {"code": "PT1D", "name": "Oeste e Vale do Tejo", "parent_iso3": "PRT"},
    {"code": "PT20", "name": "Região Autónoma dos Açores", "parent_iso3": "PRT"},
    {"code": "PT30", "name": "Região Autónoma da Madeira", "parent_iso3": "PRT"},
    {"code": "RO11", "name": "Nord-Vest", "parent_iso3": "ROU"},
    {"code": "RO12", "name": "Centru", "parent_iso3": "ROU"},
    {"code": "RO21", "name": "Nord-Est", "parent_iso3": "ROU"},
    {"code": "RO22", "name": "Sud-Est", "parent_iso3": "ROU"},
    {"code": "RO31", "name": "Sud-Muntenia", "parent_iso3": "ROU"},
    {"code": "RO32", "name": "Bucureşti-Ilfov", "parent_iso3": "ROU"},
    {"code": "RO41", "name": "Sud-Vest Oltenia", "parent_iso3": "ROU"},
    {"code": "RO42", "name": "Vest", "parent_iso3": "ROU"},
    {"code": "RS11", "name": "Beogradski region", "parent_iso3": "SRB"},
    {"code": "RS12", "name": "Region Vojvodine", "parent_iso3": "SRB"},
    {"code": "RS21", "name": "Region Sumadije i Zapadne Srbije", "parent_iso3": "SRB"},
    {"code": "RS22", "name": "Region Juzne i Istocne Srbije", "parent_iso3": "SRB"},
    {"code": "SE11", "name": "Stockholm", "parent_iso3": "SWE"},
    {"code": "SE12", "name": "Östra Mellansverige", "parent_iso3": "SWE"},
    {"code": "SE21", "name": "Småland med öarna", "parent_iso3": "SWE"},
    {"code": "SE22", "name": "Sydsverige", "parent_iso3": "SWE"},
    {"code": "SE23", "name": "Västsverige", "parent_iso3": "SWE"},
    {"code": "SE31", "name": "Norra Mellansverige", "parent_iso3": "SWE"},
    {"code": "SE32", "name": "Mellersta Norrland", "parent_iso3": "SWE"},
    {"code": "SE33", "name": "Övre Norrland", "parent_iso3": "SWE"},
    {"code": "SI03", "name": "Vzhodna Slovenija", "parent_iso3": "SVN"},
    {"code": "SI04", "name": "Zahodna Slovenija", "parent_iso3": "SVN"},
    {"code": "SK01", "name": "Bratislavský kraj", "parent_iso3": "SVK"},
    {"code": "SK02", "name": "Západné Slovensko", "parent_iso3": "SVK"},
    {"code": "SK03", "name": "Stredné Slovensko", "parent_iso3": "SVK"},
    {"code": "SK04", "name": "Východné Slovensko", "parent_iso3": "SVK"},
    {"code": "TR10", "name": "İstanbul", "parent_iso3": "TUR"},
    {"code": "TR21", "name": "Tekirdağ, Edirne, Kırklareli", "parent_iso3": "TUR"},
    {"code": "TR22", "name": "Balıkesir, Çanakkale", "parent_iso3": "TUR"},
    {"code": "TR31", "name": "İzmir", "parent_iso3": "TUR"},
    {"code": "TR32", "name": "Aydın, Denizli, Muğla", "parent_iso3": "TUR"},
    {"code": "TR33", "name": "Manisa, Afyonkarahisar, Kütahya, Uşak", "parent_iso3": "TUR"},
    {"code": "TR41", "name": "Bursa, Eskişehir, Bilecik", "parent_iso3": "TUR"},
    {"code": "TR42", "name": "Kocaeli, Sakarya, Düzce, Bolu, Yalova", "parent_iso3": "TUR"},
    {"code": "TR51", "name": "Ankara", "parent_iso3": "TUR"},
    {"code": "TR52", "name": "Konya, Karaman", "parent_iso3": "TUR"},
    {"code": "TR61", "name": "Antalya, Isparta, Burdur", "parent_iso3": "TUR"},
    {"code": "TR62", "name": "Adana, Mersin", "parent_iso3": "TUR"},
    {"code": "TR63", "name": "Hatay, Kahramanmaraş, Osmaniye", "parent_iso3": "TUR"},
    {"code": "TR71", "name": "Kırıkkale, Aksaray, Niğde, Nevşehir, Kırşehir", "parent_iso3": "TUR"},
    {"code": "TR72", "name": "Kayseri, Sivas, Yozgat", "parent_iso3": "TUR"},
    {"code": "TR81", "name": "Zonguldak, Karabük, Bartın", "parent_iso3": "TUR"},
    {"code": "TR82", "name": "Kastamonu, Çankırı, Sinop", "parent_iso3": "TUR"},
    {"code": "TR83", "name": "Samsun, Tokat, Çorum, Amasya", "parent_iso3": "TUR"},
    {"code": "TR90", "name": "Trabzon, Ordu, Giresun, Rize, Artvin, Gümüşhane", "parent_iso3": "TUR"},
    {"code": "TRA1", "name": "Erzurum, Erzincan, Bayburt", "parent_iso3": "TUR"},
    {"code": "TRA2", "name": "Ağrı, Kars, Iğdır, Ardahan", "parent_iso3": "TUR"},
    {"code": "TRB1", "name": "Malatya, Elazığ, Bingöl, Tunceli", "parent_iso3": "TUR"},
    {"code": "TRB2", "name": "Van, Muş, Bitlis, Hakkari", "parent_iso3": "TUR"},
    {"code": "TRC1", "name": "Gaziantep, Adıyaman, Kilis", "parent_iso3": "TUR"},
    {"code": "TRC2", "name": "Şanlıurfa, Diyarbakır", "parent_iso3": "TUR"},
    {"code": "TRC3", "name": "Mardin, Batman, Şırnak, Siirt", "parent_iso3": "TUR"},
]
